services:
  microservice:
    container_name: educational
    build: ./educational
    volumes:
      - ./educational/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=educational_db

  mysql:
    container_name: mysql-server
    image: mysql:8.0
    networks:
      - msexample
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=educational_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./educational/mysql/data:/var/lib/mysql
      - ./educational/mysql/initdb:/docker-entrypoint-initdb.d  # Mount init SQL files

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - msexample
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    ports:
      - "8080:80"

networks:
  msexample:
    driver: bridge

volumes:
  mysql-data:
