services:
  microservice:
    container_name: educational
    build: ./educational
    volumes:
      - ./educational/code:/usr/src/app
    networks:
      - myeducational  
    ports:
      - "${EDUCATIONAL_PORT}:${EDUCATIONAL_PORT}"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    environment:
      - EDUCATIONAL_DB_HOST=mysql-server-educational
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - EDUCATIONAL_DB_NAME=${EDUCATIONAL_DB_NAME}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mysql-server-educational
    restart: always

  mysql-server-educational:
    container_name: mysql-server-educational
    image: mysql:8.0
    networks:
      - myeducational  
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${EDUCATIONAL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    ports:
      - "${EDUCATIONAL_MYSQL_PORT}:${EDUCATIONAL_MYSQL_PORT}"
    volumes:
      - ./educational/mysql/initdb:/docker-entrypoint-initdb.d  # Mount init SQL files
      - mysql-data-educational:/var/lib/mysql

  microservice2:
    container_name: challenges
    build: ./challenges
    volumes:
      - ./challenges/code:/usr/src/app
    networks:
      - mychallenges  
    ports:
      - "${CHALLENGES_PORT}:${CHALLENGES_PORT}"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    environment:
      - CHALLENGES_DB_HOST=mysql-server-challenges
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - CHALLENGES_DB_NAME=${CHALLENGES_DB_NAME}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mysql-server-challenges
    restart: always

  mysql-server-challenges:
    container_name: mysql-server-challenges
    image: mysql:8.0
    networks:
      - mychallenges  
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${CHALLENGES_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    ports:
      - "${CHALLENGES_MYSQL_PORT}:${CHALLENGES_MYSQL_PORT}"
    volumes:
      - ./challenges/mysql/initdb:/docker-entrypoint-initdb.d  # Mount init SQL files
      - mysql-data-challenges:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - myeducational
      - mychallenges 
    environment:
      - PMA_HOSTS=mysql-server-educational,mysql-server-challenges
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8080:80"

networks:
  myeducational:
    driver: bridge
  mychallenges:
    driver: bridge

volumes:
  mysql-data-educational:
  mysql-data-challenges:
