CREATE DATABASE IF NOT EXISTS users_db;

USE users_db;

CREATE TABLE IF NOT EXISTS Statistics (
  Stat_ID INT AUTO_INCREMENT PRIMARY KEY,
  Stat_name VARCHAR(255) NOT NULL,
  Stat_value INT NOT NULL,
  User_ID INT NOT NULL,
  FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
);

