CREATE TABLE IF NOT EXISTS WeeklyStatistics (
    Stat_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Week_Start DATE NOT NULL,
    Week_End DATE NOT NULL,
    Total_CO2 INT NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
);
