CREATE TABLE IF NOT EXISTS YearlyStatistics (
    Stat_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Year INT NOT NULL,
    Month INT NOT NULL,
    Total_CO2 INT NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE
);
