CREATE TABLE AcceptedChallenges (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Challenge_ID NUMBER NOT NULL,
    accepted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    photo VARCHAR2(2083) NULL,
    CONSTRAINT fk_accepted_challenge_id FOREIGN KEY (Challenge_ID) REFERENCES Challenges(Challenge_ID)
);