CREATE DATABASE IF NOT EXISTS gallery_db;

USE gallery_db;

CREATE TABLE Art (
    art_id INT AUTO_INCREMENT PRIMARY KEY,
    gallery_id INT REFERENCES gallery(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    placeholder_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);